// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `default_device_for_target`, `default_target_for_platform`, `is_byt5_metadata`, `new`, `normalize_non_empty`, `validate_positive`, `with_details`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`

Future<G2pPlatformDefaults> g2PPlatformDefaults() =>
    G2pBridge.instance.api.crateApiG2PPlatformDefaults();

Future<G2pModelConfig> g2PDefaultConfig() =>
    G2pBridge.instance.api.crateApiG2PDefaultConfig();

Future<G2PModel> g2PModelNew({required G2pModelConfig config}) =>
    G2pBridge.instance.api.crateApiG2PModelNew(config: config);

Future<List<String>> g2PModelRun({
  required G2PModel model,
  required List<String> words,
  required String lang,
  G2pRunOptions? options,
}) => G2pBridge.instance.api.crateApiG2PModelRun(
  model: model,
  words: words,
  lang: lang,
  options: options,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<G2pModel>>
abstract class G2PModel implements RustOpaqueInterface {}

enum G2pErrorKind {
  config,
  artifact,
  tokenizer,
  tvm,
  device,
  inference,
  unknown,
}

class G2pFfiError implements FrbException {
  final G2pErrorKind kind;
  final String message;
  final String? details;

  const G2pFfiError({required this.kind, required this.message, this.details});

  @override
  int get hashCode => kind.hashCode ^ message.hashCode ^ details.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is G2pFfiError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message &&
          details == other.details;
}

class G2pModelConfig {
  final String assetRoot;
  final String checkpoint;
  final String target;
  final int maxInputBytes;
  final int maxOutputLen;
  final int batchSize;
  final String? tvmExt;
  final bool useKvCache;
  final String? device;
  final int deviceId;
  final String? tokenizerRoot;
  final String? tvmRoot;

  const G2pModelConfig({
    required this.assetRoot,
    required this.checkpoint,
    required this.target,
    required this.maxInputBytes,
    required this.maxOutputLen,
    required this.batchSize,
    this.tvmExt,
    required this.useKvCache,
    this.device,
    required this.deviceId,
    this.tokenizerRoot,
    this.tvmRoot,
  });

  static Future<G2pModelConfig> default_() =>
      G2pBridge.instance.api.crateApiG2PModelConfigDefault();

  @override
  int get hashCode =>
      assetRoot.hashCode ^
      checkpoint.hashCode ^
      target.hashCode ^
      maxInputBytes.hashCode ^
      maxOutputLen.hashCode ^
      batchSize.hashCode ^
      tvmExt.hashCode ^
      useKvCache.hashCode ^
      device.hashCode ^
      deviceId.hashCode ^
      tokenizerRoot.hashCode ^
      tvmRoot.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is G2pModelConfig &&
          runtimeType == other.runtimeType &&
          assetRoot == other.assetRoot &&
          checkpoint == other.checkpoint &&
          target == other.target &&
          maxInputBytes == other.maxInputBytes &&
          maxOutputLen == other.maxOutputLen &&
          batchSize == other.batchSize &&
          tvmExt == other.tvmExt &&
          useKvCache == other.useKvCache &&
          device == other.device &&
          deviceId == other.deviceId &&
          tokenizerRoot == other.tokenizerRoot &&
          tvmRoot == other.tvmRoot;
}

class G2pPlatformDefaults {
  final String target;
  final String device;

  const G2pPlatformDefaults({required this.target, required this.device});

  @override
  int get hashCode => target.hashCode ^ device.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is G2pPlatformDefaults &&
          runtimeType == other.runtimeType &&
          target == other.target &&
          device == other.device;
}

class G2pRunOptions {
  final bool spaceAfterColon;

  const G2pRunOptions({required this.spaceAfterColon});

  static Future<G2pRunOptions> default_() =>
      G2pBridge.instance.api.crateApiG2PRunOptionsDefault();

  @override
  int get hashCode => spaceAfterColon.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is G2pRunOptions &&
          runtimeType == other.runtimeType &&
          spaceAfterColon == other.spaceAfterColon;
}
