// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class G2pBridgeApiImplPlatform extends BaseApiImpl<G2pBridgeWire> {
  G2pBridgeApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_G2PModelPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModelPtr;

  @protected
  G2PModel
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModel(
          dynamic raw);

  @protected
  G2PModel
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModel(
          dynamic raw);

  @protected
  G2PModel
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModel(
          dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  G2pModelConfig dco_decode_box_autoadd_g_2_p_model_config(dynamic raw);

  @protected
  G2pRunOptions dco_decode_box_autoadd_g_2_p_run_options(dynamic raw);

  @protected
  G2pErrorKind dco_decode_g_2_p_error_kind(dynamic raw);

  @protected
  G2pFfiError dco_decode_g_2_p_ffi_error(dynamic raw);

  @protected
  G2pModelConfig dco_decode_g_2_p_model_config(dynamic raw);

  @protected
  G2pPlatformDefaults dco_decode_g_2_p_platform_defaults(dynamic raw);

  @protected
  G2pRunOptions dco_decode_g_2_p_run_options(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  G2pRunOptions? dco_decode_opt_box_autoadd_g_2_p_run_options(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  G2PModel
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModel(
          SseDeserializer deserializer);

  @protected
  G2PModel
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModel(
          SseDeserializer deserializer);

  @protected
  G2PModel
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModel(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  G2pModelConfig sse_decode_box_autoadd_g_2_p_model_config(
      SseDeserializer deserializer);

  @protected
  G2pRunOptions sse_decode_box_autoadd_g_2_p_run_options(
      SseDeserializer deserializer);

  @protected
  G2pErrorKind sse_decode_g_2_p_error_kind(SseDeserializer deserializer);

  @protected
  G2pFfiError sse_decode_g_2_p_ffi_error(SseDeserializer deserializer);

  @protected
  G2pModelConfig sse_decode_g_2_p_model_config(SseDeserializer deserializer);

  @protected
  G2pPlatformDefaults sse_decode_g_2_p_platform_defaults(
      SseDeserializer deserializer);

  @protected
  G2pRunOptions sse_decode_g_2_p_run_options(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  G2pRunOptions? sse_decode_opt_box_autoadd_g_2_p_run_options(
      SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModel(
          G2PModel self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModel(
          G2PModel self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModel(
          G2PModel self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_g_2_p_model_config(
      G2pModelConfig self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_g_2_p_run_options(
      G2pRunOptions self, SseSerializer serializer);

  @protected
  void sse_encode_g_2_p_error_kind(G2pErrorKind self, SseSerializer serializer);

  @protected
  void sse_encode_g_2_p_ffi_error(G2pFfiError self, SseSerializer serializer);

  @protected
  void sse_encode_g_2_p_model_config(
      G2pModelConfig self, SseSerializer serializer);

  @protected
  void sse_encode_g_2_p_platform_defaults(
      G2pPlatformDefaults self, SseSerializer serializer);

  @protected
  void sse_encode_g_2_p_run_options(
      G2pRunOptions self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_g_2_p_run_options(
      G2pRunOptions? self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class G2pBridgeWire implements BaseWire {
  factory G2pBridgeWire.fromExternalLibrary(ExternalLibrary lib) =>
      G2pBridgeWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  G2pBridgeWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModel(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModel(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModelPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_charsiug2p_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModel');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModel =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModelPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModel(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModel(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModelPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_charsiug2p_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModel');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModel =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModelPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
