// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class G2pBridge
    extends BaseEntrypoint<G2pBridgeApi, G2pBridgeApiImpl, G2pBridgeWire> {
  @internal
  static final instance = G2pBridge._();

  G2pBridge._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    G2pBridgeApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required G2pBridgeApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<G2pBridgeApiImpl, G2pBridgeWire> get apiImplConstructor =>
      G2pBridgeApiImpl.new;

  @override
  WireConstructor<G2pBridgeWire> get wireConstructor =>
      G2pBridgeWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1844494699;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'charsiug2p_g2p_ffi',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class G2pBridgeApi extends BaseApi {
  Future<G2pModelConfig> crateApiG2PDefaultConfig();

  Future<G2PModel> crateApiG2PModelNew({required G2pModelConfig config});

  Future<List<String>> crateApiG2PModelRun(
      {required G2PModel model,
      required List<String> words,
      required String lang,
      G2pRunOptions? options});

  Future<G2pPlatformDefaults> crateApiG2PPlatformDefaults();

  Future<G2pModelConfig> crateApiG2PModelConfigDefault();

  Future<G2pRunOptions> crateApiG2PRunOptionsDefault();

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_G2PModel;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_G2PModel;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_G2PModelPtr;
}

class G2pBridgeApiImpl extends G2pBridgeApiImplPlatform
    implements G2pBridgeApi {
  G2pBridgeApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<G2pModelConfig> crateApiG2PDefaultConfig() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_g_2_p_model_config,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiG2PDefaultConfigConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiG2PDefaultConfigConstMeta => const TaskConstMeta(
        debugName: "g2p_default_config",
        argNames: [],
      );

  @override
  Future<G2PModel> crateApiG2PModelNew({required G2pModelConfig config}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_g_2_p_model_config(config, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModel,
        decodeErrorData: sse_decode_g_2_p_ffi_error,
      ),
      constMeta: kCrateApiG2PModelNewConstMeta,
      argValues: [config],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiG2PModelNewConstMeta => const TaskConstMeta(
        debugName: "g2p_model_new",
        argNames: ["config"],
      );

  @override
  Future<List<String>> crateApiG2PModelRun(
      {required G2PModel model,
      required List<String> words,
      required String lang,
      G2pRunOptions? options}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModel(
            model, serializer);
        sse_encode_list_String(words, serializer);
        sse_encode_String(lang, serializer);
        sse_encode_opt_box_autoadd_g_2_p_run_options(options, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: sse_decode_g_2_p_ffi_error,
      ),
      constMeta: kCrateApiG2PModelRunConstMeta,
      argValues: [model, words, lang, options],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiG2PModelRunConstMeta => const TaskConstMeta(
        debugName: "g2p_model_run",
        argNames: ["model", "words", "lang", "options"],
      );

  @override
  Future<G2pPlatformDefaults> crateApiG2PPlatformDefaults() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_g_2_p_platform_defaults,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiG2PPlatformDefaultsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiG2PPlatformDefaultsConstMeta =>
      const TaskConstMeta(
        debugName: "g2p_platform_defaults",
        argNames: [],
      );

  @override
  Future<G2pModelConfig> crateApiG2PModelConfigDefault() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_g_2_p_model_config,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiG2PModelConfigDefaultConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiG2PModelConfigDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "g_2_p_model_config_default",
        argNames: [],
      );

  @override
  Future<G2pRunOptions> crateApiG2PRunOptionsDefault() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_g_2_p_run_options,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiG2PRunOptionsDefaultConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiG2PRunOptionsDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "g_2_p_run_options_default",
        argNames: [],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_G2PModel => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModel;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_G2PModel => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModel;

  @protected
  G2PModel
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModel(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return G2PModelImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  G2PModel
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModel(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return G2PModelImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  G2PModel
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModel(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return G2PModelImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  G2pModelConfig dco_decode_box_autoadd_g_2_p_model_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_g_2_p_model_config(raw);
  }

  @protected
  G2pRunOptions dco_decode_box_autoadd_g_2_p_run_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_g_2_p_run_options(raw);
  }

  @protected
  G2pErrorKind dco_decode_g_2_p_error_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return G2pErrorKind.values[raw as int];
  }

  @protected
  G2pFfiError dco_decode_g_2_p_ffi_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return G2pFfiError(
      kind: dco_decode_g_2_p_error_kind(arr[0]),
      message: dco_decode_String(arr[1]),
      details: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  G2pModelConfig dco_decode_g_2_p_model_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14)
      throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return G2pModelConfig(
      assetRoot: dco_decode_String(arr[0]),
      checkpoint: dco_decode_String(arr[1]),
      target: dco_decode_String(arr[2]),
      maxInputBytes: dco_decode_u_32(arr[3]),
      maxOutputLen: dco_decode_u_32(arr[4]),
      batchSize: dco_decode_u_32(arr[5]),
      tvmExt: dco_decode_opt_String(arr[6]),
      useKvCache: dco_decode_bool(arr[7]),
      device: dco_decode_opt_String(arr[8]),
      deviceId: dco_decode_i_32(arr[9]),
      tokenizerRoot: dco_decode_opt_String(arr[10]),
      tvmRoot: dco_decode_opt_String(arr[11]),
      useSystemLib: dco_decode_bool(arr[12]),
      systemLibPrefix: dco_decode_opt_String(arr[13]),
    );
  }

  @protected
  G2pPlatformDefaults dco_decode_g_2_p_platform_defaults(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return G2pPlatformDefaults(
      target: dco_decode_String(arr[0]),
      device: dco_decode_String(arr[1]),
    );
  }

  @protected
  G2pRunOptions dco_decode_g_2_p_run_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return G2pRunOptions(
      spaceAfterColon: dco_decode_bool(arr[0]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  G2pRunOptions? dco_decode_opt_box_autoadd_g_2_p_run_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_g_2_p_run_options(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  G2PModel
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModel(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return G2PModelImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  G2PModel
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModel(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return G2PModelImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  G2PModel
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModel(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return G2PModelImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  G2pModelConfig sse_decode_box_autoadd_g_2_p_model_config(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_g_2_p_model_config(deserializer));
  }

  @protected
  G2pRunOptions sse_decode_box_autoadd_g_2_p_run_options(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_g_2_p_run_options(deserializer));
  }

  @protected
  G2pErrorKind sse_decode_g_2_p_error_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return G2pErrorKind.values[inner];
  }

  @protected
  G2pFfiError sse_decode_g_2_p_ffi_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_g_2_p_error_kind(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_details = sse_decode_opt_String(deserializer);
    return G2pFfiError(
        kind: var_kind, message: var_message, details: var_details);
  }

  @protected
  G2pModelConfig sse_decode_g_2_p_model_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_assetRoot = sse_decode_String(deserializer);
    var var_checkpoint = sse_decode_String(deserializer);
    var var_target = sse_decode_String(deserializer);
    var var_maxInputBytes = sse_decode_u_32(deserializer);
    var var_maxOutputLen = sse_decode_u_32(deserializer);
    var var_batchSize = sse_decode_u_32(deserializer);
    var var_tvmExt = sse_decode_opt_String(deserializer);
    var var_useKvCache = sse_decode_bool(deserializer);
    var var_device = sse_decode_opt_String(deserializer);
    var var_deviceId = sse_decode_i_32(deserializer);
    var var_tokenizerRoot = sse_decode_opt_String(deserializer);
    var var_tvmRoot = sse_decode_opt_String(deserializer);
    var var_useSystemLib = sse_decode_bool(deserializer);
    var var_systemLibPrefix = sse_decode_opt_String(deserializer);
    return G2pModelConfig(
        assetRoot: var_assetRoot,
        checkpoint: var_checkpoint,
        target: var_target,
        maxInputBytes: var_maxInputBytes,
        maxOutputLen: var_maxOutputLen,
        batchSize: var_batchSize,
        tvmExt: var_tvmExt,
        useKvCache: var_useKvCache,
        device: var_device,
        deviceId: var_deviceId,
        tokenizerRoot: var_tokenizerRoot,
        tvmRoot: var_tvmRoot,
        useSystemLib: var_useSystemLib,
        systemLibPrefix: var_systemLibPrefix);
  }

  @protected
  G2pPlatformDefaults sse_decode_g_2_p_platform_defaults(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_target = sse_decode_String(deserializer);
    var var_device = sse_decode_String(deserializer);
    return G2pPlatformDefaults(target: var_target, device: var_device);
  }

  @protected
  G2pRunOptions sse_decode_g_2_p_run_options(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_spaceAfterColon = sse_decode_bool(deserializer);
    return G2pRunOptions(spaceAfterColon: var_spaceAfterColon);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  G2pRunOptions? sse_decode_opt_box_autoadd_g_2_p_run_options(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_g_2_p_run_options(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModel(
          G2PModel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as G2PModelImpl).frbInternalSseEncode(move: true), serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModel(
          G2PModel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as G2PModelImpl).frbInternalSseEncode(move: false), serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG2pModel(
          G2PModel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as G2PModelImpl).frbInternalSseEncode(move: null), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_g_2_p_model_config(
      G2pModelConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_g_2_p_model_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_g_2_p_run_options(
      G2pRunOptions self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_g_2_p_run_options(self, serializer);
  }

  @protected
  void sse_encode_g_2_p_error_kind(
      G2pErrorKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_g_2_p_ffi_error(G2pFfiError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_g_2_p_error_kind(self.kind, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_opt_String(self.details, serializer);
  }

  @protected
  void sse_encode_g_2_p_model_config(
      G2pModelConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.assetRoot, serializer);
    sse_encode_String(self.checkpoint, serializer);
    sse_encode_String(self.target, serializer);
    sse_encode_u_32(self.maxInputBytes, serializer);
    sse_encode_u_32(self.maxOutputLen, serializer);
    sse_encode_u_32(self.batchSize, serializer);
    sse_encode_opt_String(self.tvmExt, serializer);
    sse_encode_bool(self.useKvCache, serializer);
    sse_encode_opt_String(self.device, serializer);
    sse_encode_i_32(self.deviceId, serializer);
    sse_encode_opt_String(self.tokenizerRoot, serializer);
    sse_encode_opt_String(self.tvmRoot, serializer);
    sse_encode_bool(self.useSystemLib, serializer);
    sse_encode_opt_String(self.systemLibPrefix, serializer);
  }

  @protected
  void sse_encode_g_2_p_platform_defaults(
      G2pPlatformDefaults self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.target, serializer);
    sse_encode_String(self.device, serializer);
  }

  @protected
  void sse_encode_g_2_p_run_options(
      G2pRunOptions self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.spaceAfterColon, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_g_2_p_run_options(
      G2pRunOptions? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_g_2_p_run_options(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class G2PModelImpl extends RustOpaque implements G2PModel {
  // Not to be used by end users
  G2PModelImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  G2PModelImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        G2pBridge.instance.api.rust_arc_increment_strong_count_G2PModel,
    rustArcDecrementStrongCount:
        G2pBridge.instance.api.rust_arc_decrement_strong_count_G2PModel,
    rustArcDecrementStrongCountPtr:
        G2pBridge.instance.api.rust_arc_decrement_strong_count_G2PModelPtr,
  );
}
